# Site settings
author: Jessie Gong
title: Jessie Gong
header-img: img/home-bg.png
email: jessiegong92@gmail.com
copyright_name: Jessie Gong
description: > # this means to ignore newlines until "baseurl:"
  Developer | Columbia University | New York, NY
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  urnotjessie

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
