# Site settings
title: My first Ruby CLI Gem
header-img: img/home-bg.png
email: jessiegong92@gmail.com
copyright_name: urnotjessie
description: > # this means to ignore newlines until "baseurl:"
  keto_snack_recipes
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  urnotjessie
learn_profile: urnotjessie
email_username: jessiegong92@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
